### PR TITLE
[NCL-6854] Update typescript, lerna and rollup

### PR DESCRIPTION
**Pull request by patrikk0123**

### CODE REVIEW

**Review by DnsZhou — APPROVED** [review]
Verified on my local and also tested the function that works good. Feel free to merge it, Thanks Patrik!

**Comment by matedo1** [comment]
How `package-lock.json` files were generated in the end?

**Comment by patrikk0123** [comment]
> How `package-lock.json` files were generated in the end?

By `lerna bootstrap` command, without `--hoist` option.

**Comment by matedo1** [comment]
> > How `package-lock.json` files were generated in the end?
> 
> By `lerna bootstrap` command, without `--hoist` option.

Then we need to clarify and update README when it should(not) be used.

Is it ok to remove this option?

**Pull request merged**
